### ISSUE TITLE
LinkedRW Crashes when running

### ISSUE THREAD

**Issue by koenieee** [zeshuaro/LinkedRW#51]
LinkedRW (version 1.2.0) crashes when trying to scrape data from LinkedIn.
See last message, I also tried to increase the timeout to 30.

[1018/205149.931:INFO:CONSOLE(1)] "document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.", source: https://static-exp1.licdn.com/sc/h/br/brvu2i6m20qsgbxiefnnmzycz (1)
Traceback (most recent call last):
  File "C:\Users\Koen\AppData\Local\Programs\Python\Python38-32\Scripts\linkedrw-script.py", line 11, in <module>
    load_entry_point('linkedrw==1.2.0', 'console_scripts', 'linkedrw')()
  File "C:\Users\Koen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\linkedrw\main.py", line 37, in main
    args.method(**vars(args))
  File "C:\Users\Koen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\linkedrw\main.py", line 73, in run
    profile = scrape(driver.lower(), driver_path, email, password, output_dir, timeout)
  File "C:\Users\Koen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\linkedrw\scraper\scrape.py", line 72, in scrape
    elem = WebDriverWait(driver, timeout).until(ec.presence_of_element_located(
  File "C:\Users\Koen\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by zeshuaro** [comment]
This should be fixed in `v1.2.1`. Please update `linkedrw` to the latest version and feel free to reopen the issue if you are still facing the issue.
